#!/usr/bin/env python3
"""
Blog Content Engine — BagajPark Growth Agent

Daily: generates 3 blog post ideas + SEO keywords
Based on:
  - Current events / travel season
  - Low-competition keyword research
  - Competitor blog gaps
  - Common traveler questions

Output: reports/blog/{date}.md
"""

import json
import re
import sys
import urllib.error
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports" / "blog"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Seed keywords for SEO research
SEED_KEYWORDS = [
    "luggage storage istanbul",
    "valiz emanet ankara",
    "bag drop izmir",
    "luggage storage near me",
    "luggagestorage turkey",
    "suitcase storage",
    "baggage hold istanbul",
    "emanet bavul",
    "valiz saklama",
    "best luggage storage apps",
    "luggage storage antalya",
]

LANGUAGES = {
    "tr": {"label": "Türkçe", "prefix": ""},
    "en": {"label": "English", "prefix": "en/"},
}

def check_google_competition(keyword):
    """Quick check: how many results for this keyword?"""
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36",
    }
    url = f"https://www.google.com/search?q={urllib.parse.quote(keyword)}"
    try:
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=8) as r:
            html = r.read().decode("utf-8", errors="replace")
    except Exception:
        return None

    # Try to extract result count
    m = re.search(r'About ([\d,]+) results', html)
    if m:
        count = int(m.group(1).replace(",", ""))
        return count

    m = re.search(r'Aşağıda yaklaşık ([\d.]+) sonuç', html)
    if m:
        count = int(m.group(1).replace(".", ""))
        return count

    return None

def generate_blog_ideas():
    """Generate 3 blog post ideas based on season and gaps."""
    now = datetime.now(timezone.utc)
    month = now.month

    # Seasonal context
    if 5 <= month <= 9:
        season = "summer"
        season_label = "Yaz / Summer"
        season_angle = "peak travel season, airport crowds, hotel check-out times"
    elif month in [10, 11]:
        season = "fall"
        season_label = "Sonbahar / Fall"
        season_angle = "shoulder season, city breaks"
    else:
        season = "winter"
        season_label = "Kış / Winter"
        season_angle = "ski trips, indoor activities"

    ideas = []

    # Idea 1: City-specific guide (low competition, high conversion)
    ideas.append({
        "title_tr": f"İstanbul'da Valiz Emanet: 2026 Rehberi — Nerede, Kaç TL, Güvenli mi?",
        "title_en": "Luggage Storage in Istanbul: 2026 Guide — Where, How Much, Is It Safe?",
        "angle": f"Travelers arriving in Istanbul during {season_label} need to know where to store bags before/after hotel check-in.",
        "target_keyword_tr": "istanbul valiz emanet",
        "target_keyword_en": "luggage storage istanbul",
        "competition_check": "istanbul luggage storage",
        "type": "guide",
    })

    # Idea 2: Comparison / listicle
    ideas.append({
        "title_tr": "En İyi Valiz Emanet Uygulamaları 2026: Karşılaştırma ve İnceleme",
        "title_en": "Best Luggage Storage Apps 2026: Comparison & Review",
        "angle": f"Comparison of Bounce, Stasher, Radical Storage, and BagajPark — features, pricing, coverage, insurance.",
        "target_keyword_tr": "valiz emanet uygulaması",
        "target_keyword_en": "best luggage storage apps",
        "competition_check": "best luggage storage apps",
        "type": "comparison",
    })

    # Idea 3: Problem/solution based on season
    ideas.append({
        "title_tr": f"{season_label} Tatilinde Bavul Derdi: Check-Out ile Uçuş Arasında Ne Yapmalı?",
        "title_en": f"No More Bag Worries During {season_label} Travel: What to Do Between Check-Out and Your Flight?",
        "angle": f"Common traveler pain point: {season_angle}. Solution: book luggage storage.",
        "target_keyword_tr": "check out sonrasi valiz",
        "target_keyword_en": "luggage storage between checkout and flight",
        "competition_check": "luggage storage between checkout and flight",
        "type": "solution",
    })

    return ideas, season_label

def main():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    ideas, season = generate_blog_ideas()

    lines = [
        f"# Blog Content Engine — {today}",
        f"_Season: {season} — Generated by emanetcim-growth-agent_\n",
    ]

    # Competition check
    lines.append("## 🔍 Keyword Competition Check\n")
    for idea in ideas:
        kw = idea.get("competition_check", idea["target_keyword_en"])
        count = check_google_competition(kw)
        if count is not None:
            level = "🟢 Low" if count < 500000 else "🟡 Medium" if count < 2000000 else "🔴 High"
            lines.append(f"- **{kw}**: ~{count:,} results — {level}")
        else:
            lines.append(f"- **{kw}**: Could not check")
    lines.append("")

    # Blog ideas
    lines.append("## 📝 Suggested Blog Posts\n")
    for i, idea in enumerate(ideas, 1):
        lines.append(f"### {i}. {idea['title_en']}")
        lines.append(f"**🇹🇷 {idea['title_tr']}**")
        lines.append(f"")
        lines.append(f"**Angle:** {idea['angle']}")
        lines.append(f"**Target keywords:** `{idea['target_keyword_en']}`, `{idea['target_keyword_tr']}`")
        lines.append(f"**Type:** {idea['type']}")
        lines.append(f"**Link suggestion:** `{bagajpark_url(idea['target_keyword_en'])}`")
        lines.append("")

    lines.append("---")
    lines.append(f"Next scan: tomorrow 07:30 TRT")

    report = "\n".join(lines)
    print(report)

    report_path = REPORTS_DIR / f"{today}.md"
    with open(report_path, "w") as f:
        f.write(report)

    return 0

def bagajpark_url(keyword):
    """Generate a bagajpark.com URL for the given keyword."""
    slug = keyword.lower().replace(" ", "-")
    return f"https://bagajpark.com/en/blog/{slug}"

if __name__ == "__main__":
    sys.exit(main())
