#!/usr/bin/env python3
"""
Competitor Scanner — BagajPark Growth Agent

Daily: scans competitor websites/apps for:
  - New city expansions
  - Price changes
  - New features
  - News/acquisitions
  - Partnership announcements

Output: reports/competitors/{date}.md
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports" / "competitors"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

COMPETITORS = {
    "Bounce": "https://bounce.com",
    "Stasher": "https://stasher.com",
    "Radical Storage": "https://radicalstorage.com",
    "LuggageHero": "https://luggagehero.com",
}

def fetch_text(url, retries=2):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml",
    }
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as r:
                return r.read().decode("utf-8", errors="replace")
        except Exception:
            if attempt < retries:
                import time
                time.sleep(1)
    return None

def scan_bounce():
    """Check Bounce for new cities, blog updates"""
    findings = []
    html = fetch_text("https://bounce.com/locations")
    if not html:
        return ["⚠️ Could not fetch Bounce locations page"]

    # Count city mentions
    cities = re.findall(r'/locations/([a-z-]+)', html)
    unique_cities = set(cities)
    findings.append(f"📍 Bounce cities found on page: {len(unique_cities)}")

    # Check for Turkey presence
    turkey_related = [c for c in unique_cities if any(
        kw in c for kw in ["istanbul", "ankara", "izmir", "antalya", "turkey"])]
    if turkey_related:
        findings.append(f"🇹🇷 Bounce in Turkey: {', '.join(turkey_related)}")
    else:
        findings.append("✅ Bounce NOT yet in Turkey")

    # Check blog for recent news
    blog_html = fetch_text("https://bounce.com/blog")
    if blog_html:
        titles = re.findall(r'<h[23][^>]*>(.*?)</h[23]>', blog_html, re.DOTALL)
        if titles:
            clean = [re.sub(r'<[^>]+>', '', t).strip() for t in titles[:5]]
            findings.append(f"📰 Recent blog: {clean[0] if clean else 'N/A'}")

    return findings

def scan_stasher():
    """Check Stasher for new cities"""
    findings = []
    html = fetch_text("https://stasher.com/stores")
    if not html:
        return ["⚠️ Could not fetch Stasher page"]

    cities = re.findall(r'/stores/([a-z-]+)', html)
    unique = set(cities)
    findings.append(f"📍 Stasher cities: {len(unique)}")

    # Check blog
    blog = fetch_text("https://stasher.com/blog")
    if blog:
        titles = re.findall(r'<h[23][^>]*>(.*?)</h[23]>', blog, re.DOTALL)
        if titles:
            clean = [re.sub(r'<[^>]+>', '', t).strip() for t in titles[:3]]
            findings.append(f"📰 {clean[0] if clean else ''}")

    return findings

def scan_radical():
    """Check Radical Storage"""
    findings = []
    html = fetch_text("https://radicalstorage.com/locations")
    if html:
        cities = re.findall(r'/([a-z-]+)-luggage-storage', html)
        findings.append(f"📍 Radical Storage cities: {len(set(cities))}")
    else:
        findings.append("⚠️ Could not fetch Radical Storage")
    return findings

def scan_luggagehero():
    """Check LuggageHero"""
    findings = []
    html = fetch_text("https://luggagehero.com/locations")
    if html:
        cities = re.findall(r'/locations/([a-z-]+)', html)
        findings.append(f"📍 LuggageHero cities: {len(set(cities))}")
    else:
        findings.append("⚠️ Could not fetch LuggageHero")
    return findings

def main():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# Competitor Scan — {today}",
        f"_Generated by emanetcim-growth-agent_\n",
    ]

    lines.append("## 🏆 Bounce")
    for f in scan_bounce():
        lines.append(f"  {f}")
    lines.append("")

    lines.append("## 📦 Stasher")
    for f in scan_stasher():
        lines.append(f"  {f}")
    lines.append("")

    lines.append("## 🔴 Radical Storage")
    for f in scan_radical():
        lines.append(f"  {f}")
    lines.append("")

    lines.append("## 🧳 LuggageHero")
    for f in scan_luggagehero():
        lines.append(f"  {f}")
    lines.append("")

    lines.append("---")
    lines.append(f"Next scan: tomorrow 07:30 TRT")

    report = "\n".join(lines)
    print(report)

    # Save report
    report_path = REPORTS_DIR / f"{today}.md"
    with open(report_path, "w") as f:
        f.write(report)

    return 0

if __name__ == "__main__":
    sys.exit(main())
