#!/usr/bin/env python3
"""
Reddit Monitor — BagajPark Growth Agent

Daily: searches Reddit for unanswered luggage storage questions.
Finds posts like "where to store luggage in X" where BagajPark operates.
Output: reports/reddit/{date}.md
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports" / "reddit"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Cities where BagajPark operates (or nearby) — prioritize these
TARGET_CITIES = [
    "istanbul", "ankara", "izmir", "turkey", "antalya",
    "fethiye", "bodrum", "marmaris", "kemer", "alanya",
    "capadocia", "pamukkale", "ephesus",
]

TARGET_KEYWORDS = [
    "luggage storage",
    "store luggage",
    "store my bag",
    "bag storage",
    "leave my luggage",
    "baggage storage",
    "keep my bags",
    "locker",
    "saklama",
    "emanet",
]

EXCLUDE_SUBREDDITS = ["politics", "worldnews", "news"]

def fetch_reddit_results(query, subreddit=None, limit=5):
    """Search Reddit via Google (Reddit's own search is unreliable without API)"""
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/125.0.0.0 Safari/537.36",
        "Accept": "text/html",
    }

    site = f"site:reddit.com/r/{subreddit}" if subreddit else "site:reddit.com"
    q = f"{site} {query}"
    url = f"https://www.google.com/search?q={urllib.parse.quote(q)}&tbs=qdr:d"  # last 24h

    try:
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=10) as r:
            html = r.read().decode("utf-8", errors="replace")
    except Exception as e:
        return [], str(e)

    results = []
    # Extract Reddit post URLs and titles from Google search results
    patterns = [
        (r'<a href="/url\?q=(https?://(?:www\.)?reddit\.com/r/[^/]+/comments/[^"&]+)[^>]*>(.*?)</a>', 1),
        (r'href="(https?://(?:www\.)?reddit\.com/r/[^/]+/comments/[^"&]+)"[^>]*>(.*?)</a>', 0),
    ]

    for pattern, url_group in patterns:
        for match in re.finditer(pattern, html, re.DOTALL):
            post_url = match.group(1) if url_group == 0 else match.group(1)
            title = re.sub(r'<[^>]+>', '', match.group(2) if url_group == 0 else match.group(2)).strip()

            # Normalize URL
            post_url = post_url.split('&')[0]  # strip tracking params
            if post_url.startswith('/url?q='):
                post_url = post_url.replace('/url?q=', '').split('&')[0]

            # Decode URL encoding
            post_url = urllib.parse.unquote(post_url)

            # Skip excluded subreddits
            if any(ex in post_url.lower() for ex in EXCLUDE_SUBREDDITS):
                continue

            # Skip non-question posts
            if "?" not in title and not any(kw.lower() in title.lower() for kw in TARGET_KEYWORDS):
                continue

            results.append({"title": title, "url": post_url})
            if len(results) >= limit:
                break
        if results:
            break

    return results, None

def main():
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# Reddit Monitor — {today}",
        f"_Generated by emanetcim-growth-agent_\n",
    ]

    all_posts = []
    errors = []

    # Search for each city + keyword combination
    for city in TARGET_CITIES:
        for keyword in TARGET_KEYWORDS[:3]:  # Limit to 3 keywords per city
            query = f"{city} {keyword}"
            posts, err = fetch_reddit_results(query, limit=3)
            if err:
                errors.append(f"{query}: {err}")
            for p in posts:
                if p["url"] not in [x["url"] for x in all_posts]:
                    all_posts.append(p)

    # Also search travel subreddits specifically
    for sub in ["travel", "solotravel", "backpacking", "istanbul", "TurkeyTravel"]:
        for keyword in TARGET_KEYWORDS[:2]:
            posts, err = fetch_reddit_results(keyword, subreddit=sub, limit=3)
            if err:
                errors.append(f"r/{sub}: {err}")
            for p in posts:
                if p["url"] not in [x["url"] for x in all_posts]:
                    all_posts.append(p)

    if all_posts:
        lines.append(f"## 🔍 Found {len(all_posts)} relevant posts\n")
        for i, post in enumerate(all_posts[:15], 1):
            lines.append(f"{i}. **{post['title']}**")
            lines.append(f"   🔗 {post['url']}")
            lines.append("")
    else:
        lines.append("## 🔍 No new relevant posts found today\n")

    if errors:
        lines.append("### ⚠️ Errors")
        for e in errors[:5]:
            lines.append(f"- {e}")

    lines.append("---")
    lines.append(f"Next scan: tomorrow 07:30 TRT")

    report = "\n".join(lines)
    print(report)

    report_path = REPORTS_DIR / f"{today}.md"
    with open(report_path, "w") as f:
        f.write(report)

    return 0

if __name__ == "__main__":
    sys.exit(main())
